import {
  Wrench,
  Laptop,
  GraduationCap,
  Video,
  HandHelping,
  Camera,
  Monitor,
  PawPrint,
  Heart,
  PartyPopper,
  Car,
  Home,
  type LucideIcon,
} from "lucide-react";

export type CategoryConfig = {
  value: string;
  label: string;
  description: string;
  icon: LucideIcon;
  subcategories: string[];
};

export const CATEGORIES: CategoryConfig[] = [
  {
    value: "odd_jobs",
    label: "Odd Jobs",
    description: "Moving, cleaning, lawns, errands, and general help",
    icon: HandHelping,
    subcategories: [
      "Moving & Lifting",
      "Cleaning",
      "Lawn & Garden",
      "Errands & Delivery",
      "Assembly & Setup",
      "Event Help",
      "Junk Removal",
      "Storage Help",
      "Furniture Disassembly",
      "Other",
    ],
  },
  {
    value: "trades",
    label: "Skilled Trades",
    description: "Licensed and skilled trade services",
    icon: Wrench,
    subcategories: [
      "Electrical",
      "Plumbing",
      "Painting",
      "Carpentry",
      "Tiling",
      "Gas Fitting",
      "Roofing",
      "Landscaping",
      "Fencing",
      "Insulation",
      "Glazing",
      "General Handyman",
      "Other",
    ],
  },
  {
    value: "remote",
    label: "Remote Services",
    description: "CV review, coding help, design work, and more",
    icon: Laptop,
    subcategories: [
      "CV & Resume Review",
      "Coding & Development",
      "Graphic Design",
      "Writing & Editing",
      "Data Entry",
      "Social Media",
      "Translation",
      "Virtual Assistant",
      "SEO & Marketing",
      "Video Editing",
      "Audio Production",
      "Bookkeeping",
      "Other",
    ],
  },
  {
    value: "tutoring",
    label: "Tutoring & Mentoring",
    description: "Structured learning sessions and academic help",
    icon: GraduationCap,
    subcategories: [
      "Mathematics",
      "Science",
      "English & Writing",
      "Languages",
      "Music",
      "Computer Science",
      "Test Prep",
      "Career Mentoring",
      "Art & Drawing",
      "Cooking",
      "Life Skills",
      "Other",
    ],
  },
  {
    value: "consultation",
    label: "Consultations",
    description: "Real-time advisory and professional consultations",
    icon: Video,
    subcategories: [
      "Business Advisory",
      "Legal Guidance",
      "Financial Planning",
      "Health & Wellness",
      "Career Coaching",
      "Tech Consulting",
      "Real Estate",
      "Immigration",
      "Nutrition",
      "Other",
    ],
  },
  {
    value: "creative",
    label: "Creative & Design",
    description: "Photography, videography, graphic design, and creative work",
    icon: Camera,
    subcategories: [
      "Photography",
      "Videography",
      "Graphic Design",
      "Logo Design",
      "Illustration",
      "Animation",
      "Interior Design",
      "Fashion Design",
      "Other",
    ],
  },
  {
    value: "tech",
    label: "Tech & IT",
    description: "Computer repair, network setup, smart home, and tech support",
    icon: Monitor,
    subcategories: [
      "Computer Repair",
      "Network Setup",
      "Smart Home Installation",
      "Phone & Tablet Repair",
      "Data Recovery",
      "Website Setup",
      "IT Support",
      "Security Systems",
      "Other",
    ],
  },
  {
    value: "pet_services",
    label: "Pet Services",
    description: "Grooming, sitting, walking, training, and pet care",
    icon: PawPrint,
    subcategories: [
      "Dog Walking",
      "Pet Sitting",
      "Pet Grooming",
      "Pet Training",
      "Pet Transport",
      "Aquarium Maintenance",
      "Other",
    ],
  },
  {
    value: "health_wellness",
    label: "Health & Wellness",
    description: "Personal training, yoga, massage, and wellness services",
    icon: Heart,
    subcategories: [
      "Personal Training",
      "Yoga Instruction",
      "Massage Therapy",
      "Meditation Coaching",
      "Nutrition Coaching",
      "Physiotherapy Exercises",
      "Other",
    ],
  },
  {
    value: "events",
    label: "Events",
    description: "DJ, catering, photography, decoration, and event services",
    icon: PartyPopper,
    subcategories: [
      "DJ & Music",
      "Catering",
      "Event Photography",
      "Event Videography",
      "Decoration & Styling",
      "MC & Hosting",
      "Party Planning",
      "Sound & Lighting",
      "Other",
    ],
  },
  {
    value: "automotive",
    label: "Automotive",
    description: "Detailing, basic maintenance, car washing, and vehicle care",
    icon: Car,
    subcategories: [
      "Car Washing",
      "Car Detailing",
      "Basic Maintenance",
      "Tyre Changing",
      "Battery Replacement",
      "Dent Repair",
      "Window Tinting",
      "Other",
    ],
  },
  {
    value: "home_property",
    label: "Home & Property",
    description: "Deep cleaning, organizing, staging, inspection, and property services",
    icon: Home,
    subcategories: [
      "Deep Cleaning",
      "Organizing & Decluttering",
      "Home Staging",
      "Property Inspection",
      "Pest Control",
      "Window Cleaning",
      "Gutter Cleaning",
      "Pressure Washing",
      "Other",
    ],
  },
];

export function getCategoryConfig(value: string): CategoryConfig | undefined {
  return CATEGORIES.find((c) => c.value === value);
}
